### ISSUE TITLE
Unable to register as an External Tester on TestFlight

### ISSUE THREAD

**Issue by FStrout** [webex/webex-ios-sdk-example#12]
I am trying to register as an External Tester. I fill out the form and when I click the Register button I get the attached error.

![Screen Shot 2019-06-20 at 1 14 31 PM](https://user-images.githubusercontent.com/37194417/59871607-97d3ea00-935d-11e9-8a24-fa6855fa82e3.png)

**Comment by olivierproffit** [comment]
@FStrout Now it's working again for me. Could you try again? 
<img width="386" alt="Screen Shot 2019-07-11 at 11 55 10 AM" src="https://user-images.githubusercontent.com/15777232/61021158-deec5280-a3d2-11e9-8f5c-8e8b67cc93ca.png">

**Comment by olivierproffit** [comment]
@FStrout as it's working for us, and haven't get any feedback, I am closing this ticket. Feel free to reply if you still experiment this issue
