### ISSUE TITLE
Fail to update Signing

### ISSUE THREAD

**Issue by vielucasluu** [webex/webex-ios-sdk-example#26]
<img width="685" alt="Screen Shot 2020-11-12 at 03 55 26" src="https://user-images.githubusercontent.com/6637801/98918016-1bceca80-249b-11eb-9e0b-4736ac744b13.png">

**Comment by MrShiY** [comment]
@vielucasluu you need to configure your own account to run on a real device. The account should include an App bundle ID, two broadcast bundle ID and a group ID, so that you can run on a real device.

**Comment by vielucasluu** [comment]
Please give me region to create group ID and two boardcast bundle ID?
I do not have guideline for this.

**Comment by MrShiY** [comment]
@vielucasluu do you have Apple developer account? Creating App group is almost the same as general App IDs, two boardcast bundle ID should be generated automatically while you add broadcast upload extension. you can also change them logging in [Apple developer site](https://developer.apple.com/account/resources/identifiers/list).
<img width="859" alt="Screen Shot 2020-11-23 at 12 44 59 PM" src="https://user-images.githubusercontent.com/16798715/99929852-b5df1e80-2d89-11eb-9ab5-c4dff71e7784.png">

**Comment by MrShiY** [comment]
@vielucasluu Have you solved the previous problem yourself？

**Comment by vielucasluu** [comment]
Thank you for your support, I will check it and reply you soon.
So please explain to me, why we need active App Group and broadcast bundle.?

**Comment by MrShiY** [comment]
@vielucasluu  because screen share feature of SDK need them
