### ISSUE TITLE
Crash when start the call (Include call direct or group)

### ISSUE THREAD

**Issue by vielucasluu** [webex/webex-ios-sdk-example#27]

**Comment by vielucasluu** [comment]
webexSDK.phone.dial(self.spaceID, option: mediaOption) { [weak self] (result) in
if let strongSelf = self {
switch result {
case .success(let call):
strongSelf.currentCall = call
case .failure(let error):
if let err = error as? WebexError, case .requireHostPinOrMeetingPassword = err {
var hostKeyTextField: UITextField?
var passwordTextField: UITextField?
let alert = UIAlertController(title: "Are you the host?", message: "If you are the host, please enter host key. Otherwise, enter the meeting password.", preferredStyle: .alert)
alert.addTextField { (textFiled) in
textFiled.placeholder = "Host Key"
hostKeyTextField = textFiled
}
alert.addTextField { (textFiled) in
textFiled.placeholder = "Meeting Password"
passwordTextField = textFiled
}
alert.addAction(UIAlertAction(title: "OK", style: .default, handler: { (action) in
var isModerator = false
var pinOrPassword = passwordTextField?.text
if let hostKey = hostKeyTextField?.text, hostKey.count > 0 {
isModerator = true
pinOrPassword = hostKey
}
strongSelf.startCall()
}))
alert.addAction(UIAlertAction(title: "Cancel", style: .cancel, handler: { (action) in
strongSelf.navigationController?.popViewController(animated: true)
}))
strongSelf.present(alert, animated: true, completion: nil)

}
else {
strongSelf.navigationController?.popViewController(animated: true)
}
print("Dial call error: \(error)")
}
}
}

**Comment by MrShiY** [comment]
@vielucasluu can you provide the version you are using, and crash error message?
